### ISSUE TITLE
Feature Request: The optional ability to coerce parameters with a supplied function in request validation

### ISSUE THREAD

**Issue by quinnlangille** [SSENSE/node-framework#11]
Mimicking the `coerce` property from [Mozilla's Convict](https://github.com/mozilla/node-convict), we could pass something like:

```
  function split(separator, params) {
      return params.split(separator)
  }

  ValidateRequest({ 
      params: {
          filter: {type 'array', required: false, coerce: split('-')}
      }
  })
```

The use case in the above example is something I have just encountered when using the framework, my param contained a string (`value1-value2-value3`) which I wanted to split on the dash.  Currently, the framework's request validation only splits by comma. 

Rather than handling this at the service or repository level, it would be nice to handle inside request validation.

**Comment by RemyJeancolas** [comment]
Thanks for the proposal @quinnlangille, however we already have a `arraySeparator` parameter to handle this case (it's a comma by default if not set, in your case you can use "-" instead.
More detail **[here](https://github.com/SSENSE/node-framework/blob/master/src/http/validation/RequestValidation.ts#L22)**.
Does it cover your use case ?
